package com.nbcuni.test.cms.tests.backend.concerto.chiller.publishing.contenttype.event;

import com.nbcuni.test.cms.backend.chiller.pages.contenttype.DevelPage;
import com.nbcuni.test.cms.backend.chiller.pages.contenttype.EventPage;
import com.nbcuni.test.cms.backend.chiller.pages.contenttype.SeriesPage;
import com.nbcuni.test.cms.backend.tvecms.RokuBackEndLayer;
import com.nbcuni.test.cms.bussinesobjects.chiller.contenttype.Content;
import com.nbcuni.test.cms.bussinesobjects.chiller.contenttype.ContentTypeCreationStrategy;
import com.nbcuni.test.cms.bussinesobjects.chiller.contenttype.event.Event;
import com.nbcuni.test.cms.core.BaseAuthFlowTest;
import com.nbcuni.test.cms.tests.backend.tvecms.StaticBrandsProvider;
import com.nbcuni.test.cms.utils.jsonparsing.chiller.parser.contenttype.event.EventJson;
import com.nbcuni.test.cms.utils.jsonparsing.tvecms.RequestHelper;
import com.nbcuni.test.cms.utils.jsonparsing.tvecms.parser.publishingcontenttypes.ConcertoApiPublishingTypes;
import com.nbcuni.test.cms.verification.chiller.EventVerificator;
import com.nbcuni.test.webdriver.Utilities;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

/**
 * Created by Aleksandra_Lishaeva on 5/23/16.
 */
public class TC14683_PublishUpdatedEvent extends BaseAuthFlowTest {

    /**
     * Pre-Conditions:
     * There is a created Event content type
     * <p>
     * Steps:
     * 1.Go To CMS as Editor
     * Verify: The Editor panel is present
     * <p>
     * 2.Go to Content  and select Event from pre-condition
     * Verify: Edit Event Page is present
     * <p>
     * 3.Update all the fields per all sections and save
     * Veriy: All fields are updated be  new values<br/>
     * <p>
     * 4.Click button 'Publish' and send POST request to the Amazon API
     * Verify: The API log present 'success' status message of POST request
     * <p>
     * 5.Analize POST request for Event
     * Verify: The JSON scheme of Event looks like below with all updated values:
     * http://private-anon-96b5bee80-concertoapiingestmaster.apiary-mock.com/event
     * <p>
     * 6.Make sure that for
     * Verify: Event uuid present value from devel page of uuid field and generated by Registry service http://serive-app.nbcuni.com/content-registry/key=uuid?event::EVENT_NAME
     * Tags uuid, generated by contrib module
     * Images (of Promotion and Media fields) uuid, generated by contrib module
     * <p>
     * The UUID for Event, Tags and Images are present propper thier values at the devel Page
     */

    private Content series;
    private Content eventDefault;

    @Autowired
    @Qualifier("fullEvent")
    private ContentTypeCreationStrategy contentTypeCreationStrategy;

    @Autowired
    @Qualifier("defaultEvent")
    private ContentTypeCreationStrategy defaultEventCreationStrategy;

    @Autowired
    @Qualifier("defaultSeries")
    private ContentTypeCreationStrategy seriesCreationStrategy;

    @BeforeMethod(alwaysRun = true)
    public void initBusinessObject() {

        series = seriesCreationStrategy.createContentType();
        content = contentTypeCreationStrategy.createContentType();
        eventDefault = defaultEventCreationStrategy.createContentType();
        ((Event) content).getEventInfo().setRelatedSeries(series.getTitle());
    }

    @Test(groups = {"event_publishing"}, dataProviderClass = StaticBrandsProvider.class, dataProvider = "brandChillerDataProvider", enabled = true)
    public void testEventPublishingUpdate(String brand) {
        Event event = (Event) content;
        rokuBackEndLayer = new RokuBackEndLayer(webDriver, brand, aid);
        mainRokuAdminPage = rokuBackEndLayer.openAdminPage();

        //pre-condition
        EventPage editPage = (EventPage) rokuBackEndLayer.createContentType(eventDefault);
        editPage.publish();

        SeriesPage seriesPage = (SeriesPage) rokuBackEndLayer.createContentType(series);
        DevelPage develPage = seriesPage.openDevelPage();
        String seriesUuid = develPage.getUuid();
        event.getEventInfo().setRelatedSeriesUuid(seriesUuid);

        //create event with whole data
        editPage = (EventPage) rokuBackEndLayer.updateContent(eventDefault, content);

        //setMediaImages
        event.setMediaImages(editPage.onMediaTab().onMediaBlock().getMediaImages());

        //setSlug
        event.setSlugInfo(editPage.onSlugTab().getSlug());

        //publishing
        editPage.publish();
        String url = editPage.getLogURL(brand);
        softAssert.assertTrue(editPage.isStatusMessageShown(), "The status message is not shown after publishing", "The status message is shown after publishing", webDriver);
        //set Event uuid
        event = (Event) rokuBackEndLayer.updateContentByUuid(event);

        //Get Expected result
        EventJson expectedEvent = new EventJson().getObject(event);

        //Get Actual Post Request
        RequestHelper requestHelper = new RequestHelper();
        EventJson actualEventJson = requestHelper.getSingleParsedResponse(url, ConcertoApiPublishingTypes.EVENT);
        softAssert.assertTrue(new EventVerificator().verify(expectedEvent, actualEventJson), "The actual data is not matched", "The JSON data is matched", webDriver);
        softAssert.assertAll();
        Utilities.logInfoMessage("Test passed");

    }

    @AfterMethod(alwaysRun = true)
    public void deleteEventTC14683() {
        try {
            rokuBackEndLayer.deleteContentType(content);
        } catch (Throwable e) {
            Utilities.logSevereMessage(Utilities.convertStackTraceToString(e));
        }
    }
}
