package com.nbcuni.test.cms.pageobjectutils.entities;

public enum ProviderType {

    ACE_COMMUNICATIONS("ACE Communications"),
    ACME_COMMUNICATIONS("Acme Communications"),
    ADVANCED_CABLE_COMMUNICATIONS("Advanced Cable Communications"),
    ALGONA_MUNICIPAL_UTILITIES("Algona Municipal Utilities"),
    ALL_WEST_COMMUNICATIONS("All West Communications"),
    ALPINE_COMMUNICATIONS("Alpine Communications"),
    AMERICAN_BROADBAND("American Broadband"),
    ANTIETAM_CABLE_TELEVISION("Antietam Cable Television"),
    ARKWEST_COMMUNICATIONS("Arkwest Communications"),
    ARMSTRONG("Armstrong"),
    ARVIG("Arvig"),
    ASTOUND("Astound"),
    ATT_UVERSE("AT&T U-verse"),
    ATC_BROADBAND("ATC Broadband"),
    ATLANTIC_BROADBAND("Atlantic Broadband"),
    ATMC("ATMC"),
    BALDWIN_TELECOM("Baldwin Telecom, Inc."),
    BAY_CREEK_COMMUNICATIONS("Bay Creek Communications"),
    BEK_COMMUNICATIONS("BEK Communications"),
    BELD("BELD"),
    BEND_BROADBAND("Bend Broadband"),
    BLUERIDGE("Blueridge"),
    BROADSTRIPE("Broadstripe"),
    BTC_COMMUNICATIONS("BTC Communications"),
    BUCKEYE_CABLESYSTEM("Buckeye CableSystem"),
    BURLINGTON_TELCOM("Burlington Telecom"),
    BUTLER_BREMER_COMMUNICATIONS("Butler-Bremer Communications"),
    BVU_OPTINET("BVU Optinet"),
    C_SPIRE("C Spire"),
    CABLE_SERVICES("Cable Services Inc."),
    CABLE_TV_EAST_ALABAMA("Cable TV of East Alabama"),
    CABLE_TV_OF_STANTON("Cable TV of Stanton"),
    CABLEAMERICA("CableAmerica"),
    CAM_TEL_COMPANY("Cam-Tel Company"),
    CANBY_TELCOM("Canby Telcom"),
    CAPROCK_TV("CapRock Tv"),
    CAS_CABLE("CAS Cable"),
    CASSCOMM("CASSCOMM"),
    CC_COMMUNICATIONS("CC Communications"),
    CEDAR_FALLS_UTILITIES("Cedar Falls Utilities"),
    CELECT_BLOOMER_TELEPHONE("Celect-Bloomer Telephone Area"),
    CELECT_BRUCE_TELEPHONE("Celect-Bruce Telephone Area"),
    CELECT_CITIZENS_CONNECT("Celect-Citizens Connected Area"),
    CELECT_ELMWOOD("Celect-Elmwood/Spring Valley Area"),
    CELECT_WEST_WI("Celect-West WI Telephone Area"),
    CENTURYLINK_PRISM("CenturyLink Prism"),
    CHIPPEWA_VALLEY_CABLE("Chippewa Valley Cable"),
    CHARTER("Charter"),
    CIMTEL_CABLE("Cim-Tel Cable, LLC."),
    CINCINNATI_BELL_FIOPTICS("Cincinnati Bell Fioptics"),
    CITIZENS_CABLEVISION_FLOYD("Citizens Cablevision - Floyd, VA"),
    CITIZENS_CABLEVISION_INC("Citizens Cablevision, Inc."),
    CITIZENS_TELECOM("Citizens Telecom"),
    CITIZENS_TELEPHONE_CORPORATION("Citizens Telephone Corporation"),
    CITYLINK("CityLink"),
    CLEAR_CREEK_COMMUNICATIONS("Clear Creek Communications"),
    CLICK_CABLE_TV("Click! Cable TV"),
    CML_TELEPHONE_COOPERATIVE("CML Telephone Cooperative Association"),
    CNS("CNS"),
    COMCAST_XFINITY("Comcast XFINITY"),
    COMPORIUM("Comporium"),
    CONSALIDATED("Consolidated"),
    CONSALIDATED_COMMUNICATIONS("Consolidated Communications"),
    CONWAY_CORPORATION("Conway Corporation"),
    COX("Cox"),
    CRESTVIEW_CABLE_COMMUNICATIONS("Crestview Cable Communications"),
    CROSS_TV("Cross TV"),
    CROSSLAKE_COMMUNICATIONS("Crosslake Communications"),
    CT_COMMUNICATIONS("CT Communications"),
    CTC_BRAINERD("CTC - Brainerd MN"),
    CUNNINGHAM_TELEPHONE("Cunningham Telephone and Cable"),
    DAKOTA_CENTRAL_TELECOMMUNICATIONS("Dakota Central Telecommunications"),
    DELTA_TELEPHONE_COMPANY("Delta Telephone Company"),
    DISH("DISH"),
    DIRECT_TV("DIRECTV"),
    DOCOMO_PACIFIC("Docomo Pacific"),
    EAGLE_COMMUNICATIONS("Eagle Communications"),
    ETEX_COMMUNICATIONS("Etex Communications"),
    EAST_ARKANSAS_CABLE("East Arkansas Cable TV"),
    EASTON_UTILITIES("Easton Utilities"),
    EATEL("EATEL Video, LLC"),
    EMERY_TELCOM_VIDEO("Emery Telcom Video LLC"),
    ENDEAVOR_COMMUNICATIONS("Endeavor Communications"),
    ENTOUCH("enTouch"),
    ENVENTIS_FORMERLY_HICKORYTECH("Enventis formerly HickoryTech"),
    EPB_FIBER_OPTICS("EPB Fiber Optics"),
    FB_COMMUNICATIONS("F&amp;B Communications"),
    FLIENT_RIVER_COMMUNICATIONS("Flint River Communications"),
    FRANKFORT_PLANT_BOARD("Frankfort Plant Board"),
    FRANKLIN_TELEPHONE_COMPANY("Franklin Telephone Company"),
    FULL_CHANNEL("Full Channel, Inc."),
    GCI("GCI"),
    GIANT_COMMUNICATIONS("Giant Communications"),
    GLASGOW_EPB("Glasgow EPB"),
    GOLDEN_WEST_CABLEVISION("Golden West Cablevision"),
    GOOGLE_FIBER("Google Fiber"),
    GRANDE_COMMUNICATIONS("Grande Communications"),
    GREAT_PLAINS_COMMUNICATIONS("Great Plains Communications"),
    GTA("GTA"),
    GVTC("GVTC"),
    HARGRAY("Hargray"),
    HARLAN_MUNICIPAL_UTILITIES("Harlan Municipal Utilities"),
    HART_COMMUNICATIONS("Hart Communications"),
    HAWAIIAN_TELCOM("Hawaiian Telcom"),
    HBC("HBC"),
    HEART_OF_IOWA_COMMUNICATIONS("Heart of Iowa Communications Cooperative"),
    HICKORY_TELEPHONE("Hickory Telephone Company"),
    HOME_TOWN_CABLE("Home Town Cable"),
    HOMETEL_ENTERTAINMENT("HomeTel Entertainment, Inc."),
    HOMETELECOM("HomeTelecom"),
    HOOD_CANAL("Hood Canal Communications"),
    HOPE_COMMUNITY("Hope Community and TV Prescott Video"),
    HORIZON_CANBLE("Horizon Cable TV, Inc."),
    HOTWIRE_COMMUNICATIONS("Hotwire Communications"),
    HTC_COMMUNICATIONS_IL("HTC Communications - IL"),
    HTC_COMMUNICATIONS_IA("HTC Communications, Inc. - IA"),
    HTC_DIGITAL_CABLE("HTC Digital Cable"),
    IMON_COMMUNIATIONS("ImOn Communications"),
    INSIDE_CONNECT_CABLE("Inside Connect Cable"),
    INTERSTATE_TELECOMMUNICATIONS("Interstate Telecommunications Coop"),
    JACKSON_ENERGY_AUTHORITY("Jackson Energy Authority"),
    KALONA_COOPERATIVE_TELEPHONE("Kalona Cooperative Telephone Company"),
    KUHN_COMMUNICATIONS("Kuhn Communications, Inc."),
    LAUREL_HIGHLAND_TOTAL("Laurel Highland Total Communications, Inc."),
    LIBERTY_CABLEVISION("Liberty Cablevision of PR"),
    LIMESTONE_AND_BRACKEN("Limestone and Bracken Cablevision"),
    LOCALTEL_COMMUNICATIONS("LocalTel Communications"),
    LONG_LINES("Long Lines"),
    LONGVIEW_AND_KILGORE("Longview and Kilgore Cable TV"),
    LUMOS_NETWORKS("Lumos Networks"),
    LUS_FIBER("LUS Fiber"),
    MADISON_COMMUNICATIONS("Madison Communications"),
    MANTI_TELEPHONE_COMPANY("Manti Telephone Company"),
    MCTV("MCTV"),
    MEDIACOM("Mediacom"),
    MERRIMAC_COMMUNICATIONS("Merrimac Communications Ltd."),
    METROCAST("MetroCast"),
    METRONET("Metronet"),
    MHTC("MHTC"),
    MI_CONNECTION("MI-Connection"),
    MID_HUDSON_CABLE("Mid-Hudson Cable"),
    MID_RIVERS_COMMUNICATIONS("Mid-Rivers Communications"),
    MIDCONTINENT_COMMUNICATIONS("Midcontinent Communications"),
    MIDSTATE_COMMUNICATIONS("Midstate Communications"),
    MILFORD_COMMUNICATIONS("Milford Communications"),
    MORRIS_BROADBAND("Morris Broadband"),
    MTA_COMMUNICATIONS("MTA Communications, LLC"),
    MUS_FIBERNET("MUS FiberNET"),
    MUSCATINE_POWER("Muscatine Power &amp; Water"),
    NEBRASKA_CENTRAL_TELECOM("Nebraska Central Telecom, Inc."),
    NELSON_TELEPHONE_COOPERATIVE("Nelson Telephone Cooperative"),
    NEWWAVE_COMMUNICATIONS("NewWave Communications"),
    NEXTECH("Nex-Tech"),
    NINESTAR_CONNECT("NineStar Connect"),
    NKTELCO("NKTelco, Inc."),
    NORTEX_COMMUNICATIONS("Nortex Communications"),
    NORTHLAND_COMMUNICATIONS("Northland Communications"),
    NORWOOD_LIGHT_BROADBAND("Norwood Light Broadband"),
    NSIGHT_TELSERVICES("Nsight Telservices"),
    NUTELECOM("NU-Telecom"),
    NULINK("NuLink"),
    ONESOURCE_COMMUNICATIONS("OneSource Communications"),
    OPENBAND("OpenBand"),
    OPTLINK("OptiLink"),
    OPTIMUM("Optimum"),
    ORBITEL("Orbitel"),
    PARK_REGION_TELEPHONE("Park Region Telephone and Otter Tail Telcom"),
    PAUL_BUNYAN_COMMUNICATIONS("Paul Bunyan Communications"),
    PEMBROKE_TELEPHONE_COMPANY("Pembroke Telephone Company"),
    PHONOSCOPE_CABLE("Phonoscope Cable"),
    PINE_BLUFF_CABLE("Pine Bluff Cable TV"),
    PIONEER_COMMUNICATIONS("Pioneer Communications"),
    PIONEER_LONG_DISTANCE("Pioneer Long Distance Inc."),
    POTTAWATOMIE_TELEPHONE("Pottawatomie Telephone Co."),
    PREMIER_COMMUNICATIONS("Premier Communications, Inc."),
    RAINIER("Rainier Connect"),
    RCN("RCN"),
    REINBECK_TELECOMMUNICATIONS("Reinbeck Telecommunications Utility"),
    RESORT_TV_CABLE("Resort TV Cable"),
    RMA_BROADBAND("RMA Broadband & Cable TV"),
    ROCK_PORT_CABLEVISION("Rock Port Cablevision"),
    RTC_COMMUNICATION("RTC Communication Corp"),
    SELCO("SELCO"),
    SERVICE_ELECTRIC_BROADBAND("Service Electric Broadband Cable"),
    SERVICE_ELECTRIC_CABLE_COMMUNICATIONS("Service Electric Cable and Communications"),
    SERVICE_ELECTRIC_CABLEVISION("Service Electric Cablevision"),
    SHENTEL("Shentel"),
    SJOBERG("Sjoberg's Inc."),
    SKYBEST_TV("SkyBest TV"),
    SJOBEG_INC("Sjoberg's Inc."),
    SOUTH_CENTRAL_RURAL("South Central Rural Telephone Cooperative"),
    SOUTH_SLOPE_COOPERATIVE("South Slope Cooperative Communications"),
    SPENCER_MUNICIPAL("Spencer Municipal Utilities"),
    SRT_COMMUNICATIONS("SRT Communications, Inc."),
    SUDDENLINK("Suddenlink"),
    SUMMIT_BROADBAND("Summit Broadband"),
    SUMMER_CABLE("Sumner Cable TV"),
    SUREWEST("SureWest (Consolidated Communications)"),
    SWEETWATER_CABLE_TELEVISION("Sweetwater Cable Television Co"),
    TAHLEQUAH_CABLE("Tahlequah Cable TV"),
    TCT_WEST("TCT West, Inc."),
    TDS("TDS"),
    THE_COMMUNITY_AGENCY("The Community Agency"),
    TRI_COUNTRY_COMMUNICATIONS("Tri County Communications Cooperative"),
    TRUVISTA("TruVista"),
    TSC("TSC"),
    TULLAHOMA_UTILITIES_BOARD("Tullahoma Utilities Board"),
    TWIN_VALLEY("Twin Valley"),
    UNITED_COMMUNICATIONS("United Communications"),
    US_SONET("US Sonet"),
    USA_COMMUNICATIONS("USA Communications"),
    VALUNET("ValuNet"),
    VERIZON("Verizon"),
    VICKSBURG_VIDEO("Vicksburg Video"),
    VOLCANO_VISION("Volcano Vision, Inc."),
    VOLFIRST("VolFirst / BLTV"),
    WAITSFIELD_CABLE("Waitsfield Cable"),
    WAVE_BROADBAND("Wave Broadband"),
    WEST_CAROLINA("West Carolina Communications"),
    WEST_CENTRAL_TELEPHONE("West Central Telephone Association"),
    WEST_RIVER_COOPERATIVE("West River Cooperative Telephone Company"),
    WESTEL_SYSTEMS("WesTel Systems"),
    WESTERN_IOWA_NETWORKS("Western Iowa Networks"),
    WHITE_COUNTRY("White County Cable TV"),
    WINNEBAGO_COOPERATIVE("Winnebago Cooperative Telecom Association"),
    WOW("WOW!"),
    WTC("WTC"),
    YADTEL_TELECOM("Yadtel Telecom"),
    ZITO_MEDIA("Zito Media");

    private String providerType;

    private ProviderType(final String providerType) {
        this.providerType = providerType;
    }

    public static ProviderType get(final String value) {
        for (final ProviderType providerType : ProviderType.values()) {
            if (providerType.getProviderName().equals(value)) return providerType;
        }
        return null;
    }

    public String getProviderName() {
        return providerType;
    }
}